Sema4AI/gallery

bin/publisher/manifest.py, bin/publisher/models.py
Adds description to action info in manifest file, allowing to show it in the clients without the need of downloading entire `metadata.json` file per each action version package.
=> adding description to action info in the manifest file

actions/actions-bootstrapper/CHANGELOG.md, actions/actions-bootstrapper/LICENSE, actions/agent-connector/CHANGELOG.md, actions/agent-connector/LICENSE, actions/browsing/CHANGELOG.md, actions/email/CHANGELOG.md, actions/excel/CHANGELOG.md, actions/free-web-search/CHANGELOG.md, actions/google-calendar/CHANGELOG.md, actions/google-docs/CHANGELOG.md, actions/google-drive/CHANGELOG.md, actions/google-mail/CHANGELOG.md, actions/google-search/CHANGELOG.md, actions/google-sheets/CHANGELOG.md, actions/hubspot/CHANGELOG.md, actions/microsoft-sharepoint/CHANGELOG.md, actions/microsoft-sharepoint/LICENSE, actions/pdf/CHANGELOG.md, actions/slack/CHANGELOG.md, actions/vitality-lab-results/CHANGELOG.md, actions/vitality-medications/CHANGELOG.md, actions/vitality-workouts/CHANGELOG.md, actions/wayback-machine/CHANGELOG.md, actions/wayback-machine/LICENSE, actions/youtube/CHANGELOG.md, actions/zendesk/CHANGELOG.md
Fixed Apache 2 license refer to Sema4.ai instead of Robocorp
Fixed changelog links to semver.org and keepachangelog.com to default to https instead of http.
Only markdown and license file changes.
=> License and changelog minor fixes

.github/workflows/actions_s3_init_gallery.yml, .github/workflows/actions_s3_update_gallery.yml, actions/browsing/package.yaml, bin/publisher/build_updated_packages.py, bin/publisher/extractor.py, bin/publisher/manifest.py, bin/publisher/package_builder.py, bin/publisher/utils.py
Moves environment publishing before gallery (and `manifest.json`), and improves dependencies between jobs:
- building environments will be skipped if there is no content under `bin/publisher/gallery`
- environments publish will be skipped (instead of failing) if there are no environments in `bin/publisher/environments`
- packages publish will be skipped (instead of failing) if there are no packages in `bin/publisher/gallery`
=> gallery pipeline improvements

actions/microsoft-mail/CHANGELOG.md, actions/microsoft-mail/microsoft_mail/email_action.py, actions/microsoft-mail/package.yaml
The problem is that action `list_messages` can be called without key for the email (id) thus making returned information unusable by further email actions like forwarding or replying.
The fix will make sure that `id` is always returned even if it is not given as the requested parameter in the action call.
Can be reproduced by using published `microsoft-mail` action `list_messages` by forcing parameter `properties_to_return: "subject,from,receivedDateTime"` to the action call. This way `id` parameter (key for the email) is not returned.
=> FIX: Update 'microsoft-mail' package action 'list_messages' to always return 'id'

actions/microsoft-mail/CHANGELOG.md, actions/microsoft-mail/devdata/get_token_action.py, actions/microsoft-mail/devdata/input_list_emails.json, actions/microsoft-mail/microsoft_mail/email_action.py, actions/microsoft-mail/microsoft_mail/support.py, actions/microsoft-mail/package.yaml
The Sema4.ai OAuth2 client revealed that `list_emails` and `filter_recipients` actions missed necessary scopes basically to get `/me` endpoint result.
Testing done with Studio using Sema4.ai OAuth2 client.
=> FIX Microsoft Mail action OAuth2 scopes

actions/google-drive/CHANGELOG.md, actions/google-drive/actions.py, actions/google-drive/package.yaml, actions/google-sheets/CHANGELOG.md, actions/google-sheets/README.md, actions/google-sheets/actions.py, actions/google-sheets/package.yaml
Google-drive -> Enhanced functionality to allow searching for comments in a file by both name and ID.
Google-sheets -> Use `https://www.googleapis.com/auth/drive.file` scope instead of `https://www.googleapis.com/auth/drive` for creation.
=> Fix google-sheets scopes and google drive list comments

actions/microsoft-mail/CHANGELOG.md, actions/microsoft-mail/README.md, actions/microsoft-mail/devdata/input_flag_email.json, actions/microsoft-mail/microsoft_mail/email_action.py, actions/microsoft-mail/microsoft_mail/models.py, actions/microsoft-mail/package.yaml
For customer use case add possibility to flag and unflag messages by the email id.
This implementation has the minimum implementation to set flag status on the email. Few commented lines in the action code highlight possible upgrades that can be implemented for the action if required.
Can be tested via Sema4.ai Studio
=> `Microsoft Mail`. Add new action `flag_email`

actions/slack/CHANGELOG.md, actions/slack/actions.py, actions/slack/conversations.py, actions/slack/devdata/input_send_message_to_channel.json, actions/slack/package.yaml
On `ConversationInfo.new()` in the `while True:` loop the `cursor` was always set to `None` in the beginning of the loop. While request indicated that `next_cursor` is available and proceeded to continue the loop the next request was again made by `None` cursor instead of new cursor. This ultimately resulted in the RateLimit error from Slack web client API.
Was tested by running action `send_message_to_channel` in VSCode and in the Sema4.ai Studio.
=> `Slack`. Fix paging when creating conversation list cache

actions/browsing/CHANGELOG.md, actions/browsing/actions.py, actions/browsing/devdata/input_get_website_content.json, actions/browsing/models.py, actions/browsing/package.yaml, actions/browsing/support.py
The `get_website_content` could be called without `user_agent` parameter or by setting its value to empty dictionary and these were not handled correctly by the action.
The response size of the same action could be considerable (unnecessarily) due to empty spaces and/or line breaks within text content.
- Improved text content cleanup for all `text` properties
- Fix how parameter `user_agent` is handled for the `get_website_content` action
- Set max timeout 5 seconds for waiting for `networkidle`, but continue actions regardless
Tested with Sema4.ai VSCode extension and with Sema4.ai Studio.
=> Fix 'get_website_content' parameter handling and improve text cleanup

actions/microsoft-teams/CHANGELOG.md, actions/microsoft-teams/microsoft_teams/models.py, actions/microsoft-teams/microsoft_teams/teams_get_actions.py, actions/microsoft-teams/package.yaml
Fixed invalid return type in search_team_by_name action, from dict to list. Fixed input limit issue in get_channel_messages action. 
Published and tested with an agent in Sema4.ai Studio version 1.0.65.
Search Teams by name worked correctly and get_channel_messages limit also works correctly. 
Checklist:
=> Teams fix search teams and list channel messages

actions/excel/CHANGELOG.md, actions/excel/actions.py, actions/excel/package.yaml
`'NoneType' object has no attribute 'encode'` when workbook does not have `last_modified_by` user information.
Tested in Studio with workbook which has not been modified.
=> Fix get_workbook_schema on user missing on creator or last_modified_by

actions/microsoft-mail/CHANGELOG.md, actions/microsoft-mail/README.md, actions/microsoft-mail/devdata/input_get_email_by_id.json, actions/microsoft-mail/microsoft_mail/email_action.py, actions/microsoft-mail/package.yaml
Add the possibility of saving email attachments to a local folder. 
How added parameter `save_attachments` works:
- by default will save into the current working directory.
- if the value `downloads` is given then attachments are saved in the user's Downloads folder
- can be given local file path, on `make_dirs=True` this directory structure will be created if it does not exist
Tested in VS Code and in the Studio.
=> Microsoft Mail: Add `save_attachments` to `get_email_by_id`

.github/workflows/actions_s3_init_gallery.yml, .github/workflows/actions_s3_update_gallery.yml
Make manifest_sai.json available on S3 and in turn on CDN to be able to use from SAI Server
- https://github.com/Sema4AI/gallery/pull/120
=> Add manifest_sai.json to the S3 bucket

.github/workflows/actions_s3_init_gallery.yml, .github/workflows/actions_s3_init_gallery_sai.yml, bin/publisher/build_updated_packages.py
This pull request introduces a new GitHub Actions workflow for publishing `manifest_sai.json` and performs a cleanup of the existing workflows.
1. **New Workflow**: 
- Added a new workflow file `.github/workflows/actions_s3_init_gallery_sai.yml` that:
- Allows manual triggering via `workflow_dispatch`.
- Publishes `manifest_sai.json` to the specified S3 bucket after building the gallery.
2. **Cleanup Existing Workflow**:
- Removed the redundant copy command for `manifest_sai.json` in the existing workflow `.github/workflows/actions_s3_init_gallery.yml`.
3. **Updated Python Script**:
- Modified `bin/publisher/build_updated_packages.py` to include a new function to generate the `manifest_sai.json`.
These changes streamline the process of managing manifests by separating the publishing logic …
=> Add GitHub Actions for manifest_sai.json and Clean Up Workflow

actions/excel/CHANGELOG.md, actions/excel/actions.py, actions/excel/package.yaml
The action `create_workbook` logic was incorrect when new file needs to be created into Agent chat.
Tested with Studio v1.2.0-alpha9
=> Excel. Fix how chat file is created when using create_workbook

actions/snowflake-cortex/CHANGELOG.md, actions/snowflake-cortex/README.md, actions/snowflake-cortex/cortex_actions.py, actions/snowflake-cortex/devdata/input_cortex_analyst_message.json, actions/snowflake-cortex/devdata/input_cortex_get_search_specification.json, actions/snowflake-cortex/devdata/input_cortex_search.json, actions/snowflake-cortex/package.yaml, actions/snowflake-cortex/snowflake_actions.py, actions/snowflake-cortex/utils.py
We relied on user to write things like Warehouse name, Database, Schema and service identifier to Runbook, and then agent passing them as args to actions. This is risky and unreliable, and people tend to not even realise they are in the runbook. This PR moves those configs to be action secrets.
Tested locally on my Studio with template agents for cortex search and analyst.
- [N/A] OAuth2: I have made sure that action has necessary scopes (works in whitelisted mode)
=> Moved the cortex analyst and search query configs to secrets

agents/cortex-analyst-example/CHANGELOG.md, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/CHANGELOG.md, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/README.md, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/cortex_actions.py, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/devdata/input_cortex_analyst_message.json, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/devdata/input_cortex_get_search_specification.json, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/devdata/input_cortex_search.json, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/package.yaml, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/snowflake_actions.py, agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/utils.py, agents/cortex-analyst-example/agent-spec.yaml, agents/cortex-analyst-example/runbook.md, agents/cortex-search-example/CHANGELOG.md, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/CHANGELOG.md, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/README.md, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/cortex_actions.py, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/devdata/input_cortex_analyst_message.json, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/devdata/input_cortex_get_search_specification.json, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/devdata/input_cortex_search.json, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/package.yaml, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/snowflake_actions.py, agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/utils.py, agents/cortex-search-example/agent-spec.yaml, agents/cortex-search-example/runbook.md
Updated to cortex actions 1.0.1 where the configurations are now secrets, instead of being in the Runbook.
My local Studio
=> Updated Cortex templates to use latest action pack with secrets

actions/microsoft-excel/CHANGELOG.md, actions/microsoft-excel/microsoft_excel/add_worksheet_action.py, actions/microsoft-excel/microsoft_excel/create_workbook_action.py, actions/microsoft-excel/microsoft_excel/get_worksheet_action.py, actions/microsoft-excel/microsoft_excel/update_range_action.py, actions/microsoft-excel/package.yaml
LLM fails to call the action `update_range` with correct schema (thus the actual action is never called).
Value for `operation` parameter was given a value, which is not supported by the action definition.
Modified how `operation` is defined for the action.
The `_action` postfix has been removed from the action names.
Replicated the issue with Studio 1.2.0-alpha11 using OpenAI GTP-4o model. 
A fix was tested using the same.
=> Fix Excel 365 `update range` action with llm

actions/microsoft-excel/CHANGELOG.md, actions/microsoft-excel/microsoft_excel/_client.py, actions/microsoft-excel/microsoft_excel/add_worksheet_action.py, actions/microsoft-excel/microsoft_excel/create_workbook_action.py, actions/microsoft-excel/microsoft_excel/get_workbook_action.py, actions/microsoft-excel/microsoft_excel/update_range_action.py, actions/microsoft-excel/package.yaml
Action renaming in version 2.0.0 broke action `create_workbook`.
Tested in Studio 1.20-alpha11
=> Fix issue caused by action renaming

bin/publisher/whitelist.json
Dropped from standard whitelist:
- Actions: "vitality-lab-results", "vitality-medications", "vitality-workouts", 
-
=> drop vitality actions

actions/snowflake-cortex-analyst/CHANGELOG.md, actions/snowflake-cortex-analyst/cortex_actions.py, actions/snowflake-cortex-analyst/devdata/input_ask_cortex_analyst.json, actions/snowflake-cortex-analyst/devdata/input_snowflake_execute_query.json, actions/snowflake-cortex-analyst/package.yaml
If user copies stage path for semantic model file from Snowsight, it contains quotes. That broke the ask cortex analyst action. Fixed to treat quotes and whitespaces properly.
Tested locally in SDK with three scenarios, no quotes, quotes and whitespaces. Same in Studio.
=> Cortex Analyst: Updated to treat stage paths properly

.github/workflows/agents_s3_update_gallery.yaml
Neither aws s3 cp nor sync actually prevent overwriting existing files
This is a relatively new thing in S3: https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-writes.html
..but even that did not work, so simple curl head check for the overwrite protection.
- Made a test location on S3 > Ran update
- Checked manifests
- v1 manifest, not changed, v2 got the new fields 
- Verified the overwrite protection logic (pic below)
=> Fixing agent GHA
