Sema4AI/gallery

- actions/hubspot/CHANGELOG.md
- actions/hubspot/hubspot_client/models.py
- actions/hubspot/package.yaml
Fix Hubspot search filters schema
> Fix Hubspot search filters schema

- actions/actions-bootstrapper/CHANGELOG.md
- actions/actions-bootstrapper/package.yaml
- actions/browsing/CHANGELOG.md
- actions/browsing/package.yaml
- actions/excel/CHANGELOG.md
- actions/excel/package.yaml
- actions/google-calendar/CHANGELOG.md
- actions/google-calendar/package.yaml
- actions/google-docs/CHANGELOG.md
- actions/google-docs/package.yaml
- actions/google-drive/CHANGELOG.md
- actions/google-drive/package.yaml
- actions/google-mail/CHANGELOG.md
- actions/google-mail/package.yaml
- actions/google-search/CHANGELOG.md
- actions/google-search/package.yaml
- actions/google-sheets/CHANGELOG.md
- actions/google-sheets/package.yaml
- actions/hubspot/CHANGELOG.md
- actions/hubspot/package.yaml
- actions/microsoft-sharepoint/CHANGELOG.md
- actions/microsoft-sharepoint/package.yaml
- actions/zendesk/CHANGELOG.md
- actions/zendesk/package.yaml
> updated package descriptions

- actions/google-drive/CHANGELOG.md
- actions/google-drive/actions.py
- actions/google-drive/models.py
- actions/google-drive/package.yaml
Add the ability to search in shared drives
Link to the Linear Issue: https://linear.app/sema4ai/issue/DEV-923/google-drive-can-not-access-shared-folders
Testing instruction in Linear ticket.
> Add the ability to search in shared drives

- actions/excel/CHANGELOG.md
- actions/excel/README.md
- actions/excel/actions.py
- actions/excel/models.py
- actions/excel/package.yaml
Fix and improve excel operations
> Fix and improve excel operations

- .github/workflows/runbooks_s3_update.yml
- .gitignore
- runbooks/README.md
- runbooks/manifest.json
- runbooks/runbook-from-scratch.md
- runbooks/runbook-template-action-writer.md
- runbooks/runbook-template-vitality.md
- runbooks/runbook-template-wayback.md
Added runbook templates for Runbook Editor.
- manifest.json needs to be manually updated when new templates are added
- Pipeline pushes to: https://cdn.sema4.ai/gallery/runbooks/manifest.json
Does not affect other gallery actions etc.
> Runbook templates and pipeline

- runbooks/README.md
- runbooks/runbook-from-scratch.md
Update to the runbook templates for Studio.
Updated readme guide for runbooks
No tests, as long as these are valid markdown that is enough
> Update to the default runbook content

- runbooks/manifest.json
- runbooks/runbook-template-action-writer.md
- runbooks/runbook-template-vitality.md
- runbooks/runbook-template-wayback.md
- Updated runbook templates to match the agent templates in Studio
- Added scratch template as a selectable template in the manifest.json
No easy way to test in Studio atm. used VS Code markdown preview to check the runbook content
> Runbook template update

- actions/README.md
> Update email description

- actions/hubspot/package.yaml
> Fix Hubspot package name

- actions/microsoft-mail/README.md
> Fix a readme link

- actions/microsoft-calendar/README.md
- actions/microsoft-excel/README.md
- actions/microsoft-onedrive/README.md
- actions/microsoft-sharepoint/README.md
- actions/microsoft-teams/README.md
Fixes links to authentication links for:
* microsoft-calendar
* microsoft-excel
* microsoft-onedrive
* microsoft-sharepoint
* microsoft-teams
> fix documentation links

- bin/publisher/build_all_packages.py
- bin/publisher/build_updated_packages.py
> Remove extra param from generate_actions_manifest_for_sai

- bin/publisher/build_updated_packages.py
> Fix manifest_sai.json naming

- agents/cortex-analyst-example/agent-spec.yaml
> Update agent-spec.yaml version to 0.0.2

- bin/publisher/agents_manifest.py
- bin/publisher/tools.py
> Add actions metadata to agents manifest

- bin/publisher/whitelist.json
> Update whitelist.json to include Serper

- actions/snowflake-cortex/CHANGELOG.md
- actions/snowflake-cortex/package.yaml
> Snowflake-cortex action updates to sema4ai-data v1.0.1 to fix the private key handling

- agents/cortex-analyst-example/CHANGELOG.md
- agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/CHANGELOG.md
- agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/cortex_actions.py
- agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/package.yaml
- agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/snowflake_actions.py
- agents/cortex-analyst-example/actions/Sema4.ai/snowflake-cortex/utils.py
- agents/cortex-analyst-example/agent-spec.yaml
- agents/cortex-analyst-example/runbook.md
- agents/cortex-search-example/CHANGELOG.md
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/CHANGELOG.md
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/cortex_actions.py
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/package.yaml
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/snowflake_actions.py
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex/utils.py
- agents/cortex-search-example/agent-spec.yaml
- agents/cortex-search-example/runbook.md
> Updated cortex templates to latest action version

- agents/action-writer-agent/agent-spec.yaml
- agents/agent-writer-agent/agent-spec.yaml
- agents/cortex-analyst-example/agent-spec.yaml
- agents/cortex-search-example/agent-spec.yaml
- agents/sales-contact-finder/agent-spec.yaml
- agents/similar-company-finder/agent-spec.yaml
- agents/wayback-machine-agent/agent-spec.yaml
- bin/publisher/tools.py
> Update to latest agent cli and fix typo

- actions/snowflake-cortex/CHANGELOG.md
- actions/snowflake-cortex/package.yaml
> Bump snowflake cortex action package version to contain latest changes

- actions/google-search/CHANGELOG.md
- actions/google-search/actions.py
- actions/google-search/package.yaml
- Fixed the docstring, typo potentially confusing LLM
- Return changed to object the docstring to match
> Google Search v1.0.4

- actions/browsing/CHANGELOG.md
- actions/perplexity/CHANGELOG.md
> Add missing changelogs

- actions/google-calendar/CHANGELOG.md
- actions/google-calendar/package.yaml
- actions/google-docs/CHANGELOG.md
- actions/google-docs/package.yaml
- actions/google-drive/CHANGELOG.md
- actions/google-drive/package.yaml
- actions/google-mail/CHANGELOG.md
- actions/google-mail/package.yaml
- actions/google-search/CHANGELOG.md
- actions/google-search/package.yaml
- actions/google-sheets/CHANGELOG.md
- actions/google-sheets/package.yaml
> Add EAI rules for Google packages

- actions/browsing/CHANGELOG.md
- actions/browsing/actions.py
- actions/browsing/devdata/input_download_file.json
- actions/browsing/devdata/input_fill_elements.json
- actions/browsing/devdata/input_get_website_content.json
- actions/browsing/package.yaml
- actions/browsing/support.py
> Use Sema4ai websites for devdata

- actions/snowflake-cortex-search/CHANGELOG.md
- actions/snowflake-cortex-search/cortex_actions.py
- actions/snowflake-cortex-search/devdata/input_cortex_get_search_specification.json
- actions/snowflake-cortex-search/devdata/input_cortex_search.json
- actions/snowflake-cortex-search/package.yaml
- actions/snowflake-cortex-search/utils.py
- actions/snowflake-data/CHANGELOG.md
- actions/snowflake-data/devdata/input_snowflake_execute_query.json
- actions/snowflake-data/devdata/input_snowflake_get_columns.json
- actions/snowflake-data/devdata/input_snowflake_get_databases.json
- actions/snowflake-data/devdata/input_snowflake_get_schemas.json
- actions/snowflake-data/devdata/input_snowflake_get_tables.json
- actions/snowflake-data/package.yaml
- actions/snowflake-data/snowflake_actions.py
- actions/snowflake-data/utils.py
Fixed issue when values are given lowercase
Tested in Cursor locally
> Lowercase fix for Cortex Search and Snowflake Data packages

- agents/action-writer-agent/actions/Sema4.ai/agent-connector/package.yaml
- agents/action-writer-agent/actions/Sema4.ai/browsing/package.yaml
- agents/action-writer-agent/agent-spec.yaml
- agents/agent-writer-agent/actions/Sema4.ai/browsing/package.yaml
- agents/agent-writer-agent/agent-spec.yaml
- agents/sales-contact-finder/actions/Sema4.ai/browsing/package.yaml
- agents/sales-contact-finder/agent-spec.yaml
- agents/wayback-machine-agent/actions/Sema4.ai/browsing/package.yaml
- agents/wayback-machine-agent/agent-spec.yaml
> Fix action versions for agents

- actions/zendesk/CHANGELOG.md
- actions/zendesk/actions.py
- actions/zendesk/client.py
- actions/zendesk/models.py
- actions/zendesk/package.yaml
Tested in VSCode with input jsons and with Studio 1.3.0 different alpha versions
ZD ticket with deleted user
ZD ticket with system comments
> Add ZD organization data

- actions/snowflake-cortex-search/.gitignore
- actions/snowflake-cortex-search/CHANGELOG.md
- actions/snowflake-cortex-search/cortex_actions.py
- actions/snowflake-cortex-search/package.yaml
- agents/cortex-search-example/CHANGELOG.md
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/.gitignore
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/CHANGELOG.md
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/cortex_actions.py
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/package.yaml
- agents/cortex-search-example/agent-spec.yaml
Problem:
Cortex Search template agent failing when it calls cortex_search
Error:
```
validation-error: The received input arguments (sent in the body) do not conform to the expected API. Details: '["ROOM_TYPE", "AMENITIES", "PRICE", "CANCELLATION_POLICY"]' is not valid under any of the given schemas Failed validating 'anyOf' in schema['properties']['columns']: {'anyOf': [{'items': {}, 'type': 'array'}, {'type': 'null'}], 'title': 'Columns', 'description': 'The columns to return. These columns must be based on ' 'the columns returned by ' 'cortex_get_search_specification.', 'default': None} On instance['columns']: '["ROOM_TYPE", "AMENITIES", "PRICE", "CANCELLATION_POLICY"]'
```
Fix: Added pydantic type for cortex_search request arg
- …
> Cortex search fix

- actions/snowflake-cortex-search/CHANGELOG.md
- actions/snowflake-cortex-search/cortex_actions.py
- actions/snowflake-cortex-search/package.yaml
Cortex Search action to work with v2 agent server
> Fix from @jjhenkel

- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/CHANGELOG.md
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/cortex_actions.py
- agents/cortex-search-example/actions/Sema4.ai/snowflake-cortex-search/package.yaml
- agents/cortex-search-example/agent-spec.yaml
Updated Cortex Search Agent to use the updated action package
Ran the agent according to the docs guide at:
https://sema4.ai/docs/team-edition/templates/template-search
https://github.com/user-attachments/assets/1c57abc4-8f1c-46e3-89ba-2b7f15d39d22
> Updated Cortex Search action

- actions/google-drive/.gitignore
- actions/google-drive/CHANGELOG.md
- actions/google-drive/actions.py
- actions/google-drive/devdata/input_get_files_by_query.json
- actions/google-drive/devdata/input_upload_file.json
- actions/google-drive/models.py
- actions/google-drive/package.yaml
- New `upload_file` action to upload files to Google Drive with support for:
- File selection via chat interface
- Optional parent folder specification
- Optional file sharing with customizable roles
- Full support for shared drives
- Dependency versions updated.
- Improved `get_files_by_query` action:
- Now supports returning only basic file info, searching all drives, and saving results as CSV
- Added support for searching by parent folder name in queries (e.g., "'My Folder' in parents")
- Improved error handling and reporting
Tested via Cursor and Sema.ai Studio 1.2.9
> Add upload_file and modify get_files_by_query

- actions/README.md
Add missing packages and update some descriptions
> Update actions README.md

- actions/browsing/CHANGELOG.md
- actions/browsing/README.md
- actions/browsing/actions.py
- actions/browsing/package.yaml
Enhanced the `download_file` action to automatically attach downloaded files to the chat conversation using the sema4ai.actions chat module. This feature allows downloaded files to be immediately available in the conversation for further processing and reference, improving the user experience by eliminating the need to manually handle file attachments.
**Key Changes:**
- Added `chat` import from `sema4ai.actions`
- Modified `download_file` function to automatically attach files to chat after successful download
- Files are attached using `chat.attach_file_content()` with the filename and binary data
- Updated status messages to reflect chat integration
**Dependencies:**
- `sema4ai.actions` chat module (already included in the project dependencies)
To test this functionality, you can:
1. …
> Added support for adding downloaded files to the agent chat
